security:
    encoders:
        Sunshine\OrganizationBundle\Entity\User:
            algorithm: bcrypt

    providers:
        sunshine_user_provider:
            entity:
                class: SunshineOrganizationBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout:
                path: /logout
                target: /
            pattern: ^/
            provider: sunshine_user_provider
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin/, role: ROLE_ADMIN }
