services:
    sunshine.companytype.translator:
        class: Sunshine\OrganizationBundle\Form\CompanyType
        arguments: ['@translator']
        tags:
            - { name: form.type, alias: sunshine_company_type_translator}